# CartPole + CALSET supervised labels (shorter run)
# Usage:
#   python run_experiment.py -c configs/cartpole_large_X_calset_15k_6k.yaml

mode: train
experiment_name: cartpole_large_X_15k_6k
experiment_class: DeepReach
dynamics_class: CartPole
minWith: target

u_max: 2000
x_bound: 6
xdot_bound: 5
thetadot_bound: 5
set_mode: avoid

data_root: /common/users/ss5772/DeepReach/deepreach/cartpole_pybullet
trajectory_uniform_sampling: true
supervised_labels_file: cal_set.txt
num_supervised: 128
supervised_value_safe: -1.0
supervised_value_unsafe: 1.0
supervised_weight: 1.0

tMin: 0.0
tMax: 10.0
numpoints: 1000

num_epochs: 15000
pretrain: true
pretrain_iters: 6000
lr: 7e-5
num_hl: 2
num_nl: 96
model: sine
steps_til_summary: 500
epochs_til_ckpt: 1000

device: "cuda:0"
seed: 0
